"""empty message

Revision ID: 0d349d18ffc3
Revises: 82e8e8050fe6
Create Date: 2024-08-17 13:50:06.629918

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d349d18ffc3'
down_revision = '82e8e8050fe6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movies', schema=None) as batch_op:
        batch_op.drop_column('production_companies')
        batch_op.drop_column('director')
        batch_op.drop_column('runtime')
        batch_op.drop_column('tagline')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tagline', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('runtime', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('director', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('production_companies', sa.TEXT(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
