"""empty message

Revision ID: 82e8e8050fe6
Revises: 4a4efd7ad46b
Create Date: 2024-08-17 08:41:24.730593

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82e8e8050fe6'
down_revision = '4a4efd7ad46b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('runtime', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('original_language', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('tagline', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('director', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('production_companies', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movies', schema=None) as batch_op:
        batch_op.drop_column('production_companies')
        batch_op.drop_column('director')
        batch_op.drop_column('tagline')
        batch_op.drop_column('original_language')
        batch_op.drop_column('runtime')

    # ### end Alembic commands ###
