"""Initial migration

Revision ID: f957ad8ad06f
Revises: 
Create Date: 2024-08-12 15:29:09.994807

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f957ad8ad06f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movie_actors',
    sa.Column('movie_id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['actors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('movie_id', 'actor_id')
    )
    op.create_table('movie_genres',
    sa.Column('movie_id', sa.Integer(), nullable=False),
    sa.Column('genre_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['genre_id'], ['genres.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('movie_id', 'genre_id')
    )
    op.drop_table('movieactors')
    op.drop_table('moviegenres')
    with op.batch_alter_table('ratings', schema=None) as batch_op:
        batch_op.alter_column('rating',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ratings', schema=None) as batch_op:
        batch_op.alter_column('rating',
               existing_type=sa.INTEGER(),
               nullable=True)

    op.create_table('moviegenres',
    sa.Column('movie_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('genre_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['genre_id'], ['genres.id'], name='moviegenres_genre_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], name='moviegenres_movie_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('movie_id', 'genre_id', name='moviegenres_pkey')
    )
    op.create_table('movieactors',
    sa.Column('movie_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('actor_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['actors.id'], name='movieactors_actor_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], name='movieactors_movie_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('movie_id', 'actor_id', name='movieactors_pkey')
    )
    op.drop_table('movie_genres')
    op.drop_table('movie_actors')
    # ### end Alembic commands ###
